CREATE TABLE REGION (
    R_REGIONKEY INTEGER PRIMARY KEY,
    R_NAME VARCHAR
);

CREATE TABLE NATION (
    N_NATIONKEY INTEGER PRIMARY KEY,
    N_NAME VARCHAR,
    N_REGIONKEY INTEGER,
    FOREIGN KEY (N_REGIONKEY) REFERENCES REGION(R_REGIONKEY)
);

CREATE TABLE CUSTOMER (
    C_CUSTKEY INTEGER PRIMARY KEY,
    C_NAME VARCHAR,
    C_NATIONKEY INTEGER,
    FOREIGN KEY (C_NATIONKEY) REFERENCES NATION(N_NATIONKEY)
);

CREATE TABLE ORDERS (
    O_ORDERKEY INTEGER PRIMARY KEY,
    O_CUSTKEY INTEGER,
    O_ORDERDATE DATE,
    FOREIGN KEY (O_CUSTKEY) REFERENCES CUSTOMER(C_CUSTKEY)
);

CREATE TABLE SUPPLIER (
    S_SUPPKEY INTEGER PRIMARY KEY,
    S_NAME VARCHAR,
    S_NATIONKEY INTEGER,
    FOREIGN KEY (S_NATIONKEY) REFERENCES NATION(N_NATIONKEY)
);

CREATE TABLE LINEITEM (
    L_ORDERKEY INTEGER,
    L_SUPPKEY INTEGER,
    L_EXTENDEDPRICE DECIMAL(10,2),
    L_DISCOUNT DECIMAL(10,2),
    FOREIGN KEY (L_ORDERKEY) REFERENCES ORDERS(O_ORDERKEY),
    FOREIGN KEY (L_SUPPKEY) REFERENCES SUPPLIER(S_SUPPKEY)
);

INSERT INTO REGION VALUES 
(1, 'AMERICA'),
(2, 'EUROPE');

INSERT INTO NATION VALUES 
(1, 'USA', 1),
(2, 'CANADA', 1),
(3, 'FRANCE', 2);

INSERT INTO CUSTOMER VALUES 
(101, 'Alice', 1),
(102, 'Bob', 2),
(103, 'Charlie', 3);

INSERT INTO ORDERS VALUES 
(1001, 101, '2024-01-10'),
(1002, 102, '2024-01-15'),
(1003, 103, '2024-02-01');

INSERT INTO SUPPLIER VALUES 
(201, 'Supplier A', 1),
(202, 'Supplier B', 2),
(203, 'Supplier C', 3);

INSERT INTO LINEITEM VALUES 
(1001, 201, 500.00, 0.05), 
(1002, 202, 300.00, 0.10), 
(1003, 203, 200.00, 0.00);



PRAGMA enable_profiling;
PRAGMA enable_profile;
SET enable_profiling = 'json';
SET profile_output = '/tmp/duckdb_profile.json';


SELECT 
    N.N_NAME AS Nation,
    SUM(L.L_EXTENDEDPRICE * (1 - L.L_DISCOUNT)) AS Revenue
FROM CUSTOMER C
JOIN ORDERS O ON C.C_CUSTKEY = O.O_CUSTKEY
JOIN LINEITEM L ON O.O_ORDERKEY = L.L_ORDERKEY
JOIN SUPPLIER S ON L.L_SUPPKEY = S.S_SUPPKEY
JOIN NATION N ON S.S_NATIONKEY = N.N_NATIONKEY
JOIN REGION R ON N.N_REGIONKEY = R.R_REGIONKEY
WHERE R.R_NAME = 'AMERICA'
AND O.O_ORDERDATE BETWEEN '2024-01-01' AND '2024-12-31'
GROUP BY N.N_NAME
ORDER BY Revenue DESC;
